CREATE TABLE tb_user(
    user_id BIGINT NOT NULL AUTO_INCREMENT COMMENT'用户id',
    username VARCHAR(50) NOT NULL COMMENT'用户名',
    passwords VARCHAR(50) NOT NULL COMMENT'密码',
    PRIMARY KEY(user_id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT'用户信息表'